name: Create Docker image for HTML translation service (dev)

on:
  push:
    tags:
      - '**'

jobs:
  build-prod:
    name: Create Docker image for HTML translation service (${{ github.ref_name }})
    runs-on: ubuntu-latest
    if: "!contains(github.ref, '-dev')"
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SUBMODULE_ACCESS_KEY }}
          submodules: recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/oko-press/oko-html-translation-service:${{ github.ref_name }}
